import type { MetadataRoute } from "next";

/**
 * PWA manifest. Next generates /manifest.webmanifest from this file
 * automatically. Most-visible effect: when a user adds Klazly to
 * their Android home screen, the installed app uses these values
 * (name, short name, theme colour) instead of falling back to the
 * page title and a generic icon.
 *
 * Apple iOS reads <meta name="apple-mobile-web-app-title"> instead
 * (set via Metadata.appleWebApp in src/app/layout.tsx) — both paths
 * coexist so each platform sees the canonical name.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Klazly · Cổng Phụ Huynh",
    short_name: "Klazly",
    description: "Cổng Phụ Huynh cho trung tâm tiếng Anh tại Việt Nam.",
    // When launched from the home screen, skip the marketing site.
    // /post-login is a server-side router: signed-out → /login,
    // signed-in → role-correct portal (admin/teacher/parent/super-admin).
    // The ?utm_source=pwa marks it as an installed-app launch in analytics.
    start_url: "/post-login?utm_source=pwa",
    scope: "/",
    display: "standalone",
    background_color: "#ffffff",
    // Navy — matches the dark app chrome (was the pre-redesign blue).
    theme_color: "#0f172a",
    lang: "vi",
    // Wordmark icon set generated by scripts/icon-factory.mjs. The
    // maskable variant keeps the wordmark inside launchers'
    // circular/squircle crops.
    icons: [
      {
        src: "/icon-192.png",
        type: "image/png",
        sizes: "192x192",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "any",
      },
      {
        src: "/icon-512-maskable.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "maskable",
      },
    ],
  };
}
