-- AUTO-GENERATED by scripts/concat-migrations.mjs — do not edit by hand.
-- Full schema + migrations for a fresh NON-PROD Supabase. Paste into the
-- SQL editor and run. Does NOT include demo data (npm run db:seed) or the
-- optional worksheets-private flip.


-- ==========================================================================
-- schema.sql
-- ==========================================================================
-- Parent Portal — Postgres schema with Row Level Security.
-- Run once in Supabase SQL editor for a fresh project.

-- ==========================================================================
-- Extensions and enums
-- ==========================================================================

create extension if not exists "uuid-ossp";

do $$ begin
  create type user_role as enum ('admin', 'teacher', 'parent');
exception when duplicate_object then null; end $$;

do $$ begin
  create type behavior_rating as enum ('great', 'good', 'okay', 'needs_attention');
exception when duplicate_object then null; end $$;

do $$ begin
  create type subscription_status as enum ('trial', 'active', 'past_due', 'canceled', 'expired');
exception when duplicate_object then null; end $$;
-- If the type existed before 'expired' was added, ensure it's present.
-- ALTER TYPE ... ADD VALUE is idempotent with IF NOT EXISTS and must
-- run outside any open transaction in older Postgres — Supabase Studio
-- handles this fine when executed as a standalone statement.
alter type subscription_status add value if not exists 'expired';

-- Internal-only tier tracking (see db/founding-center.sql for full
-- context). 'standard' is everyone; 'founding' is the hand-picked
-- pilot cohort at a discounted lifetime rate; 'design_partner' is
-- free-forever in exchange for ongoing product input.
do $$ begin
  create type plan_tier as enum ('standard', 'founding', 'design_partner');
exception when duplicate_object then null; end $$;

-- ==========================================================================
-- Tables
-- ==========================================================================

create table if not exists public.centers (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  logo_url text,
  contact_email text,
  contact_phone text,
  subscription_status subscription_status not null default 'trial',
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  -- email or phone (or both) — at least one required. Phone-only
  -- accounts exist so Vietnamese parents without email can still log
  -- in. See db/users-phone.sql for the synthetic-email workaround on
  -- the Supabase Auth side.
  email text,
  phone text,
  full_name text not null,
  role user_role not null,
  center_id uuid not null references public.centers(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint users_email_or_phone_required
    check (email is not null or phone is not null)
);
create index if not exists users_center_id_idx on public.users(center_id);
create index if not exists users_role_idx on public.users(role);
create unique index if not exists users_center_email_uniq
  on public.users (center_id, lower(email))
  where email is not null;
create unique index if not exists users_center_phone_uniq
  on public.users (center_id, phone)
  where phone is not null;
create index if not exists users_phone_idx
  on public.users (phone)
  where phone is not null;

create table if not exists public.classes (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  name text not null,
  teacher_id uuid references public.users(id) on delete set null,
  schedule_text text,
  created_at timestamptz not null default now()
);
create index if not exists classes_center_id_idx on public.classes(center_id);
create index if not exists classes_teacher_id_idx on public.classes(teacher_id);

create table if not exists public.students (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  class_id uuid references public.classes(id) on delete set null,
  full_name text not null,
  age int check (age is null or (age >= 0 and age <= 30)),
  parent_user_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists students_center_id_idx on public.students(center_id);
create index if not exists students_class_id_idx on public.students(class_id);
create index if not exists students_parent_user_id_idx on public.students(parent_user_id);

create table if not exists public.lessons (
  id uuid primary key default uuid_generate_v4(),
  class_id uuid not null references public.classes(id) on delete cascade,
  -- teacher_id is nullable + SET NULL so a teacher who logged lessons can
  -- still be removed; their historical lessons stay (parents need the
  -- record) and the attribution becomes "—". See lessons-teacher-id-nullable.sql.
  teacher_id uuid references public.users(id) on delete set null,
  lesson_date date not null,
  vocabulary text,
  grammar_point text,
  speaking_activity text,
  homework text,
  general_note text,
  created_at timestamptz not null default now()
);
create index if not exists lessons_class_id_idx on public.lessons(class_id);
create index if not exists lessons_class_date_idx on public.lessons(class_id, lesson_date desc);

create table if not exists public.student_lesson_updates (
  id uuid primary key default uuid_generate_v4(),
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  behavior_rating behavior_rating,
  individual_note text,
  homework_completed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (lesson_id, student_id)
);
create index if not exists slu_lesson_idx on public.student_lesson_updates(lesson_id);
create index if not exists slu_student_idx on public.student_lesson_updates(student_id);

-- Subscription lifecycle columns (also added incrementally via
-- db/subscription-plan.sql, trial.sql, subscription-lifecycle.sql).
-- Listed here so a fresh deploy from schema.sql alone gets the full
-- shape. The trial_ends_at column on centers is set when a trial
-- begins; subscription_started_at/ends_at + last_payment_at +
-- next_billing_at track the paid window once the center converts.
create table if not exists public.audit_log (
  id bigserial primary key,
  user_id uuid references public.users(id) on delete set null,
  center_id uuid references public.centers(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_log_center_idx on public.audit_log(center_id, created_at desc);
-- Index used by the lazy-expire query in /super-admin (see
-- src/lib/subscription.ts):
--   centers where subscription_status='trial' and trial_ends_at<now()
create index if not exists centers_trial_expiry_idx
  on public.centers (trial_ends_at)
  where subscription_status = 'trial';

-- ==========================================================================
-- Helper functions used by RLS policies.
-- SECURITY DEFINER lets these read public.users without re-triggering RLS,
-- which would cause infinite recursion in the policies that call them.
-- ==========================================================================

create or replace function public.current_user_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = auth.uid()
$$;

create or replace function public.current_user_center_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select center_id from public.users where id = auth.uid()
$$;

-- ==========================================================================
-- Enable RLS on every table.
-- ==========================================================================

alter table public.centers                enable row level security;
alter table public.users                  enable row level security;
alter table public.classes                enable row level security;
alter table public.students               enable row level security;
alter table public.lessons                enable row level security;
alter table public.student_lesson_updates enable row level security;
alter table public.audit_log              enable row level security;

-- ==========================================================================
-- Policies: centers
-- A user can see their own center. Only service role mutates centers.
-- ==========================================================================

drop policy if exists "centers_select_own" on public.centers;
create policy "centers_select_own"
  on public.centers for select
  using (id = public.current_user_center_id());

-- ==========================================================================
-- Policies: users (profiles)
-- Anyone in the same center can read user profiles (needed for "Teacher: Anh Tu" labels etc).
-- Mutations go through admin endpoints with service role.
-- ==========================================================================

drop policy if exists "users_select_same_center" on public.users;
create policy "users_select_same_center"
  on public.users for select
  using (center_id = public.current_user_center_id());

-- ==========================================================================
-- Policies: classes
-- Admin: any class in their center.
-- Teacher: classes they teach.
-- Parent: classes containing their child(ren).
-- ==========================================================================

drop policy if exists "classes_select" on public.classes;
create policy "classes_select"
  on public.classes for select
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (public.current_user_role() = 'teacher' and teacher_id = auth.uid())
      or (
        public.current_user_role() = 'parent'
        and exists (
          select 1 from public.students s
          where s.class_id = classes.id and s.parent_user_id = auth.uid()
        )
      )
    )
  );

drop policy if exists "classes_admin_write" on public.classes;
create policy "classes_admin_write"
  on public.classes for all
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() = 'admin'
  )
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() = 'admin'
  );

-- ==========================================================================
-- Policies: students
-- Admin: any student in their center.
-- Teacher: students in classes they teach.
-- Parent: only their own child.
-- ==========================================================================

drop policy if exists "students_select" on public.students;
create policy "students_select"
  on public.students for select
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (
        public.current_user_role() = 'teacher'
        and exists (
          select 1 from public.classes c
          where c.id = students.class_id and c.teacher_id = auth.uid()
        )
      )
      or (
        public.current_user_role() = 'parent'
        and parent_user_id = auth.uid()
      )
    )
  );

drop policy if exists "students_admin_write" on public.students;
create policy "students_admin_write"
  on public.students for all
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() = 'admin'
  )
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() = 'admin'
  );

-- ==========================================================================
-- Policies: lessons
-- Admin: any lesson in their center.
-- Teacher: lessons in their classes (read + write).
-- Parent: lessons in their child's class (read only).
-- ==========================================================================

drop policy if exists "lessons_select" on public.lessons;
create policy "lessons_select"
  on public.lessons for select
  using (
    exists (
      select 1 from public.classes c
      where c.id = lessons.class_id
        and c.center_id = public.current_user_center_id()
        and (
          public.current_user_role() = 'admin'
          or (public.current_user_role() = 'teacher' and c.teacher_id = auth.uid())
          or (
            public.current_user_role() = 'parent'
            and exists (
              select 1 from public.students s
              where s.class_id = c.id and s.parent_user_id = auth.uid()
            )
          )
        )
    )
  );

drop policy if exists "lessons_teacher_write" on public.lessons;
create policy "lessons_teacher_write"
  on public.lessons for all
  using (
    exists (
      select 1 from public.classes c
      where c.id = lessons.class_id
        and c.center_id = public.current_user_center_id()
        and (
          public.current_user_role() = 'admin'
          or (public.current_user_role() = 'teacher' and c.teacher_id = auth.uid())
        )
    )
  )
  with check (
    teacher_id = auth.uid()
    or public.current_user_role() = 'admin'
  );

-- ==========================================================================
-- Policies: student_lesson_updates
-- Admin: all in their center.
-- Teacher: rows for lessons in their classes.
-- Parent: rows for their own child only.
-- ==========================================================================

drop policy if exists "slu_select" on public.student_lesson_updates;
create policy "slu_select"
  on public.student_lesson_updates for select
  using (
    exists (
      select 1
      from public.lessons l
      join public.classes c on c.id = l.class_id
      where l.id = student_lesson_updates.lesson_id
        and c.center_id = public.current_user_center_id()
        and (
          public.current_user_role() = 'admin'
          or (public.current_user_role() = 'teacher' and c.teacher_id = auth.uid())
          or (
            public.current_user_role() = 'parent'
            and exists (
              select 1 from public.students s
              where s.id = student_lesson_updates.student_id
                and s.parent_user_id = auth.uid()
            )
          )
        )
    )
  );

drop policy if exists "slu_teacher_write" on public.student_lesson_updates;
create policy "slu_teacher_write"
  on public.student_lesson_updates for all
  using (
    exists (
      select 1
      from public.lessons l
      join public.classes c on c.id = l.class_id
      where l.id = student_lesson_updates.lesson_id
        and c.center_id = public.current_user_center_id()
        and (
          public.current_user_role() = 'admin'
          or (public.current_user_role() = 'teacher' and c.teacher_id = auth.uid())
        )
    )
  )
  with check (
    exists (
      select 1
      from public.lessons l
      join public.classes c on c.id = l.class_id
      where l.id = student_lesson_updates.lesson_id
        and c.center_id = public.current_user_center_id()
        and (
          public.current_user_role() = 'admin'
          or (public.current_user_role() = 'teacher' and c.teacher_id = auth.uid())
        )
    )
  );

-- ==========================================================================
-- Policies: audit_log
-- Admins read their center's log; writes happen via service role only.
-- ==========================================================================

drop policy if exists "audit_admin_select" on public.audit_log;
create policy "audit_admin_select"
  on public.audit_log for select
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() = 'admin'
  );

-- ==========================================================================
-- storage.sql
-- ==========================================================================
-- Storage setup. Run once after the main schema.sql in the Supabase SQL editor.

-- Public bucket for center logos. We make it public so <img> tags can load
-- the logo without signed URLs. Uploads go through the server (service role),
-- so we don't need any insert/update policies for the anon role.

insert into storage.buckets (id, name, public)
values ('logos', 'logos', true)
on conflict (id) do nothing;

drop policy if exists "Public can read logos" on storage.objects;
create policy "Public can read logos"
  on storage.objects for select
  using (bucket_id = 'logos');

-- ==========================================================================
-- worksheets.sql
-- ==========================================================================
-- Worksheet library: PDFs / images uploaded by a center, attachable to lessons.
-- Run after schema.sql.

-- Storage bucket (public read so parents can open the file by URL).
insert into storage.buckets (id, name, public)
values ('worksheets', 'worksheets', true)
on conflict (id) do nothing;

drop policy if exists "Public can read worksheets" on storage.objects;
create policy "Public can read worksheets"
  on storage.objects for select
  using (bucket_id = 'worksheets');

-- Library table.
create table if not exists public.worksheets (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  uploaded_by uuid references public.users(id) on delete set null,
  name text not null,
  storage_path text not null,
  public_url text not null,
  file_type text not null,
  size_bytes int not null,
  created_at timestamptz not null default now()
);

create index if not exists worksheets_center_idx on public.worksheets(center_id);

alter table public.worksheets enable row level security;

drop policy if exists "worksheets_select" on public.worksheets;
create policy "worksheets_select"
  on public.worksheets for select
  using (center_id = public.current_user_center_id());

drop policy if exists "worksheets_write" on public.worksheets;
create policy "worksheets_write"
  on public.worksheets for all
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  )
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  );

-- Attach a worksheet to a lesson (single worksheet per lesson for now).
alter table public.lessons
  add column if not exists worksheet_id uuid
    references public.worksheets(id) on delete set null;

-- ==========================================================================
-- lesson-templates.sql
-- ==========================================================================
-- Lesson templates: teachers save common lesson content (vocabulary, grammar,
-- etc.) as a template and pre-fill the lesson form on subsequent classes.
-- Per-center scope so any teacher in the center can use any template.
-- Run after schema.sql.

create table if not exists public.lesson_templates (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  created_by uuid references public.users(id) on delete set null,
  name text not null,
  vocabulary text,
  grammar_point text,
  speaking_activity text,
  homework text,
  general_note text,
  created_at timestamptz not null default now()
);

create index if not exists lesson_templates_center_idx
  on public.lesson_templates(center_id);

alter table public.lesson_templates enable row level security;

drop policy if exists "templates_select" on public.lesson_templates;
create policy "templates_select"
  on public.lesson_templates for select
  using (center_id = public.current_user_center_id());

drop policy if exists "templates_write" on public.lesson_templates;
create policy "templates_write"
  on public.lesson_templates for all
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  )
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  );

-- ==========================================================================
-- messages.sql
-- ==========================================================================
-- Private parent ↔ teacher message thread, per student. Replaces the
-- shared-Zalo-group dynamic where one upset parent can spread mood to the
-- whole class. Each thread is scoped to one student: the parent(s) linked
-- to that student and the teacher who owns the student's class can
-- exchange messages; nobody else sees them.

create table if not exists public.parent_teacher_messages (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  sender_user_id uuid not null references public.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint ptm_body_len check (
    char_length(body) > 0 and char_length(body) <= 2000
  )
);

create index if not exists ptm_student_id_idx
  on public.parent_teacher_messages(student_id, created_at desc);
create index if not exists ptm_center_id_idx
  on public.parent_teacher_messages(center_id);
create index if not exists ptm_sender_idx
  on public.parent_teacher_messages(sender_user_id);

alter table public.parent_teacher_messages enable row level security;

-- Parents: can read messages about their own children.
drop policy if exists "ptm_parent_read" on public.parent_teacher_messages;
create policy "ptm_parent_read"
  on public.parent_teacher_messages for select
  using (
    public.current_user_role() = 'parent'
    and exists (
      select 1 from public.students s
      where s.id = parent_teacher_messages.student_id
        and s.parent_user_id = auth.uid()
    )
  );

-- Parents: can send a message about their own child. The sender_user_id
-- must be themselves.
drop policy if exists "ptm_parent_write" on public.parent_teacher_messages;
create policy "ptm_parent_write"
  on public.parent_teacher_messages for insert
  with check (
    public.current_user_role() = 'parent'
    and sender_user_id = auth.uid()
    and exists (
      select 1 from public.students s
      where s.id = parent_teacher_messages.student_id
        and s.parent_user_id = auth.uid()
    )
  );

-- Teachers: can read messages about students in classes they teach.
drop policy if exists "ptm_teacher_read" on public.parent_teacher_messages;
create policy "ptm_teacher_read"
  on public.parent_teacher_messages for select
  using (
    public.current_user_role() = 'teacher'
    and exists (
      select 1 from public.students s
      join public.classes c on c.id = s.class_id
      where s.id = parent_teacher_messages.student_id
        and c.teacher_id = auth.uid()
    )
  );

-- Teachers: can send a message about a student in a class they teach.
drop policy if exists "ptm_teacher_write" on public.parent_teacher_messages;
create policy "ptm_teacher_write"
  on public.parent_teacher_messages for insert
  with check (
    public.current_user_role() = 'teacher'
    and sender_user_id = auth.uid()
    and exists (
      select 1 from public.students s
      join public.classes c on c.id = s.class_id
      where s.id = parent_teacher_messages.student_id
        and c.teacher_id = auth.uid()
    )
  );

-- Admin: full read/write within their center.
drop policy if exists "ptm_admin_all" on public.parent_teacher_messages;
create policy "ptm_admin_all"
  on public.parent_teacher_messages for all
  using (
    public.current_user_role() = 'admin'
    and center_id = public.current_user_center_id()
  )
  with check (
    public.current_user_role() = 'admin'
    and center_id = public.current_user_center_id()
  );

-- Allow either party to mark messages they can see as read (sets read_at).
drop policy if exists "ptm_update_read" on public.parent_teacher_messages;
create policy "ptm_update_read"
  on public.parent_teacher_messages for update
  using (
    (
      public.current_user_role() = 'parent'
      and exists (
        select 1 from public.students s
        where s.id = parent_teacher_messages.student_id
          and s.parent_user_id = auth.uid()
      )
    )
    or (
      public.current_user_role() = 'teacher'
      and exists (
        select 1 from public.students s
        join public.classes c on c.id = s.class_id
        where s.id = parent_teacher_messages.student_id
          and c.teacher_id = auth.uid()
      )
    )
    or (
      public.current_user_role() = 'admin'
      and center_id = public.current_user_center_id()
    )
  );

-- ==========================================================================
-- trial.sql
-- ==========================================================================
-- Trial expiry tracking. Run once after schema.sql.

alter table public.centers
  add column if not exists trial_ends_at timestamptz;

-- Backfill: if a center has subscription_status = 'trial' and no trial_ends_at,
-- set it to 14 days from creation (so existing demo data isn't already expired).
update public.centers
   set trial_ends_at = created_at + interval '14 days'
 where subscription_status = 'trial'
   and trial_ends_at is null;

-- ==========================================================================
-- subscription-plan.sql
-- ==========================================================================
-- Add subscription_plan to centers so the super-admin can see (and set)
-- which paid tier each center is on. Values match the landing page's
-- three-tier pricing: "monthly" (1 month), "six_months", "annual" (12).
-- Optional: a center on trial usually has plan = null until they convert.
--
-- Idempotent: safe to re-run.

alter table public.centers
  add column if not exists subscription_plan text;

-- Optional sanity constraint. Drop+recreate to make it idempotent.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'centers_subscription_plan_check'
  ) then
    alter table public.centers
      add constraint centers_subscription_plan_check
      check (
        subscription_plan is null
        or subscription_plan in ('monthly', 'six_months', 'annual')
      );
  end if;
end $$;

-- ==========================================================================
-- subscription-lifecycle.sql
-- ==========================================================================
-- Subscription lifecycle tracking columns.
--
-- The earlier migration (subscription-plan.sql + trial.sql) added
--   subscription_status subscription_status  -- enum: trial|active|past_due|canceled
--   subscription_plan text                   -- 'monthly' | 'six_months' | 'annual'
--   trial_ends_at timestamptz
--
-- This migration completes the picture:
--   • 'expired' added to the subscription_status enum (different from
--     'canceled': canceled = user opted out; expired = trial/sub
--     period ran out)
--   • subscription_started_at / subscription_ends_at — paid window
--   • last_payment_at / next_billing_at — billing trail
--   • Index to make the lazy-expire query (find trials past their end
--     date) cheap on a list of all centers
--
-- Idempotent.

-- Add 'expired' to the existing subscription_status enum. ALTER TYPE
-- ... ADD VALUE IF NOT EXISTS is itself idempotent and ignored when
-- the value already exists. Must run as a standalone statement (not
-- inside a DO block) because ADD VALUE can't run inside a
-- transaction in older Postgres versions.
alter type subscription_status add value if not exists 'expired';

alter table public.centers
  add column if not exists subscription_started_at timestamptz,
  add column if not exists subscription_ends_at timestamptz,
  add column if not exists last_payment_at timestamptz,
  add column if not exists next_billing_at timestamptz;

-- Lazy-expire index: the super-admin page does
--   select id, trial_ends_at from centers
--    where subscription_status = 'trial' and trial_ends_at < now()
-- on every render, then issues an UPDATE for any rows it finds. This
-- partial index keeps that lookup constant-time as the centers table
-- grows.
create index if not exists centers_trial_expiry_idx
  on public.centers (trial_ends_at)
  where subscription_status = 'trial';

-- NOTE: A previous version of this file added a CHECK constraint on
-- subscription_status. That constraint was redundant with the enum
-- and is removed here so DBs that already have it don't carry dead
-- code. Safe to no-op if it was never created.
alter table public.centers
  drop constraint if exists centers_subscription_status_check;

-- ==========================================================================
-- pause-and-cancel.sql
-- ==========================================================================
-- Pause + Cancel for the super-admin operations bar.
--
--   subscription_status='paused'  : reversible — center loses access
--                                   until reactivated. Billing stops.
--   subscription_status='canceled': permanent archive. cancelled_at
--                                   timestamps when the cancel ran so
--                                   reporting + support can answer
--                                   "when did this center leave?".
--
-- 'canceled' (American spelling) already exists in the enum; we use it
-- as-is rather than introducing a 'cancelled' alias. cancelled_at is
-- the new column.
--
-- Idempotent — safe to re-run.

-- 'paused' enum value. Postgres requires this to run outside a
-- transaction in older versions; Supabase's SQL editor handles that
-- automatically.
alter type subscription_status add value if not exists 'paused';

-- Stamp the moment a center is permanently cancelled. Null for
-- everyone else; nullable to keep the column add safe.
alter table public.centers
  add column if not exists cancelled_at timestamptz;

-- Force PostgREST to reload its schema cache so the new column is
-- visible immediately. Without this, the server actions can take a
-- minute or two to notice cancelled_at exists and would fall through
-- their tolerant-strip retries unnecessarily.
notify pgrst, 'reload schema';

-- ==========================================================================
-- pending-renewal.sql
-- ==========================================================================
-- subscription_status='pending_renewal' for the super-admin renewal
-- flow. Triggered automatically when a paid center's
-- subscription_ends_at passes — the lazy-expire pass on /super-admin
-- flips them from 'active' to 'pending_renewal' so the operator gets
-- a visible nudge to renew (manual ZaloPay / bank transfer collection
-- after a Zalo conversation — never auto-charged).
--
-- Distinct from:
--   'expired'  — trial ran out, lock screen shown to users
--   'past_due' — implies payment failure (we don't auto-charge, so
--                we don't write this status from the auto pass)
--   'canceled' — operator-initiated permanent archive
--
-- Idempotent.
alter type subscription_status add value if not exists 'pending_renewal';

notify pgrst, 'reload schema';

-- ==========================================================================
-- report-settings.sql
-- ==========================================================================
-- Per-center customisation for the printable parent report. Centers can:
--   * add a short intro paragraph below the report title
--   * add a footer note (eg. confidentiality, inquiries)
--   * hide the 30-day summary card on print
--   * hide the signature block (some centers only email reports)
--   * relabel the two signature lines (eg. "Director" / "Class teacher" /
--     "Parent / Guardian")
-- Run after schema.sql.

alter table public.centers
  add column if not exists report_intro_text text,
  add column if not exists report_footer_text text,
  add column if not exists report_show_summary boolean not null default true,
  add column if not exists report_show_signatures boolean not null default true,
  add column if not exists report_signature_label_left text,
  add column if not exists report_signature_label_right text;

-- ==========================================================================
-- users-phone.sql
-- ==========================================================================
-- Phone-or-email auth migration.
-- Vietnamese parents and teachers commonly don't have a working email
-- address but everyone has a phone number (typically tied to Zalo). This
-- migration adds a phone column to public.users and relaxes the email
-- NOT NULL constraint so accounts can be created with phone alone.
--
-- Auth integration note: Supabase Auth still requires an email or phone
-- on every account, and native phone auth needs an SMS provider wired
-- up (Twilio / Vonage / eSMS.vn) which we don't have yet. The app uses
-- a "synthetic email" workaround: when a user is phone-only, we mint
-- a Supabase email like "+84901234567@phone.parent-portal.local" so
-- auth.admin.createUser succeeds, and store the real phone here. The
-- login form normalizes phone input and resolves it to the auth email
-- via public.users.phone before signInWithPassword. When SMS auth ever
-- ships, we can swap the synthetic-email pattern for native phone auth
-- without users noticing.
--
-- Idempotent: every statement guards on IF [NOT] EXISTS / DROP IF EXISTS.

-- 1. Relax email NOT NULL so phone-only accounts can be inserted.
alter table public.users
  alter column email drop not null;

-- 2. Add the phone column. Stores canonical "+84901234567" format —
--    normalization happens in app code (src/lib/phone.ts) before insert
--    so the DB only ever sees the canonical value.
alter table public.users
  add column if not exists phone text;

-- 3. CHECK constraint: at least one contact method must be set on every
--    user row. Replaces the implicit NOT NULL on email.
alter table public.users
  drop constraint if exists users_email_or_phone_required;
alter table public.users
  add constraint users_email_or_phone_required
  check (email is not null or phone is not null);

-- 4. Per-center uniqueness on email (case-insensitive) and phone.
--    Allows the same person to appear in multiple centers (a parent
--    whose kids attend two different schools) but blocks duplicates
--    within a single center. Partial indexes skip null values.
create unique index if not exists users_center_email_uniq
  on public.users (center_id, lower(email))
  where email is not null;

create unique index if not exists users_center_phone_uniq
  on public.users (center_id, phone)
  where phone is not null;

-- 5. Phone lookup index for login: users type their phone, app
--    normalizes it, looks up the row to find the auth email, signs in.
create index if not exists users_phone_idx
  on public.users (phone)
  where phone is not null;

-- ==========================================================================
-- lessons-teacher-id-nullable.sql
-- ==========================================================================
-- lessons.teacher_id was originally NOT NULL with ON DELETE RESTRICT.
-- That made it impossible to ever delete a teacher who'd logged a
-- lesson — the admin "remove teacher" action silently failed, and the
-- super-admin "delete center" action did even worse (it destroyed
-- auth.users while leaving the center, because the cascade hit RESTRICT
-- and the JS code didn't check the error).
--
-- The right pattern for audit data is SET NULL: when a teacher is
-- removed, their historical lessons stay (preserving the parent-facing
-- record) but the attribution becomes null. The UI shows "—" for
-- those rows.
--
-- This migration is idempotent.

-- 1. Drop NOT NULL so SET NULL can actually fire.
alter table public.lessons
  alter column teacher_id drop not null;

-- 2. Replace the FK with the SET NULL variant. Postgres lets you drop
--    and re-add inside the same transaction without losing data.
alter table public.lessons
  drop constraint if exists lessons_teacher_id_fkey;

alter table public.lessons
  add constraint lessons_teacher_id_fkey
  foreign key (teacher_id) references public.users(id)
  on delete set null;

-- ==========================================================================
-- student-level.sql
-- ==========================================================================
-- Per-student "overall level" so teachers and admins can see at a
-- glance how each student is doing overall, without needing to
-- read every lesson note. Three values: good / okay / needs_attention.
-- Run after schema.sql.

alter table public.students
  add column if not exists overall_level text;

-- Constrain values (skip silently if already constrained).
do $$
begin
  alter table public.students
    add constraint students_overall_level_check
    check (
      overall_level in ('good', 'okay', 'needs_attention')
      or overall_level is null
    );
exception when duplicate_object then null;
end $$;

-- ==========================================================================
-- student-lesson-updates-unique.sql
-- ==========================================================================
-- Race fix: two concurrent updateLesson calls would each do a delete +
-- insert. The second caller's delete blew away rows the first had just
-- inserted, and either both succeeded with duplicates or one failed.
--
-- Fix has two parts:
--   1. Dedupe any existing duplicates, keeping the newest row by
--      created_at per (lesson_id, student_id). Older row loses.
--   2. Add a UNIQUE constraint so future inserts can use upsert with
--      onConflict, which the app code now does. Concurrent updates
--      serialise on the constraint instead of clobbering each other.
--
-- Idempotent: safe to re-run.

-- 1) Dedupe
delete from public.student_lesson_updates a
using public.student_lesson_updates b
where a.id <> b.id
  and a.lesson_id = b.lesson_id
  and a.student_id = b.student_id
  and a.created_at < b.created_at;

-- 2) Unique constraint
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'student_lesson_updates_lesson_student_unique'
  ) then
    alter table public.student_lesson_updates
      add constraint student_lesson_updates_lesson_student_unique
      unique (lesson_id, student_id);
  end if;
end $$;

-- ==========================================================================
-- lesson-topic.sql
-- ==========================================================================
-- Optional short topic / title for a lesson, e.g. "My Home", "At the Zoo".
-- Shown to parents alongside the Unit + Lesson identifier so they have a
-- clearer sense of what the class covered. Run after lesson-unit.sql.

alter table public.lessons
  add column if not exists topic text;

-- ==========================================================================
-- lesson-unit.sql
-- ==========================================================================
-- Structured lesson identifier: separate "unit" and "lesson number" fields
-- so parents see something like "Bài 1 — Phần 2" instead of having to read
-- all the vocab/grammar to recognize the lesson.
-- Run after schema.sql.

alter table public.lessons
  add column if not exists unit text;

alter table public.lessons
  add column if not exists lesson_number text;

-- ==========================================================================
-- class-program.sql
-- ==========================================================================
-- Program / track per class (Cambridge KET, PET, FCE, IELTS, TOEIC,
-- English Communication, Young Learners). The admin dashboard groups
-- classes by this so the owner sees how big each program is at a glance.
-- Optional. Run after schema.sql.

alter table public.classes
  add column if not exists program text;

create index if not exists classes_program_idx on public.classes(program);

-- ==========================================================================
-- class-book.sql
-- ==========================================================================
-- Curriculum book per class (e.g. "Family and Friends 2", "Solutions Pre-Intermediate").
-- Shown on the admin dashboard so the owner can see at a glance which book each
-- class is studying. Optional. Run after schema.sql.

alter table public.classes
  add column if not exists book text;

-- ==========================================================================
-- center-branding.sql
-- ==========================================================================
-- Per-center branding customization for the parent PDF report.
-- The existing columns (logo_url, report_intro_text, report_footer_text,
-- report_show_summary, report_show_signatures) already let a center
-- customize a lot of the printable report; this migration adds the
-- two pieces the Branding settings page needs:
--
--   brand_color       hex string used by the PDF accent bar and
--                     section-heading underlines, plus the
--                     auto-initials circle when no logo is set.
--                     Falls back to the platform default #2563EB
--                     when null.
--
--   show_pdf_credit   toggle for the small "Created with Cổng Phụ
--                     Huynh" credit line at the bottom of the PDF.
--                     Defaults to true; centers who want a fully
--                     white-label feel can flip it off.
--
-- Idempotent.

alter table public.centers
  add column if not exists brand_color text,
  add column if not exists show_pdf_credit boolean not null default true;

-- Sanity check: brand_color must be a 7-char hex string (#RRGGBB)
-- or null. Cheaper to enforce at the DB layer than to chase bad
-- input from old settings forms.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'centers_brand_color_format_check'
  ) then
    alter table public.centers
      add constraint centers_brand_color_format_check
      check (brand_color is null or brand_color ~ '^#[0-9A-Fa-f]{6}$');
  end if;
end $$;

-- ==========================================================================
-- center-notes.sql
-- ==========================================================================
-- Internal notes per center. Visible only to the super-admin; used to
-- capture sales/support context ("paid via BIDV 2026-04", "wants Excel
-- export", "referred by ...").
--
-- Privacy: row-level security on `centers` lets a center admin SELECT
-- their own row, so a column-scoped revoke is needed to keep the notes
-- column private. Without this, an admin could fetch the super-admin's
-- private notes about them via the REST API.
--
-- Idempotent: safe to re-run.

alter table public.centers
  add column if not exists notes text;

-- Only the service-role client (used by the super-admin server actions)
-- may read the notes column. anon/authenticated lose access. RLS still
-- applies, but a SELECT that asks for `notes` from a normal client will
-- now fail with "permission denied for column notes" — which is what we
-- want.
revoke select (notes) on public.centers from anon, authenticated;
grant select (notes) on public.centers to service_role;
grant update (notes) on public.centers to service_role;

-- ==========================================================================
-- center-programs.sql
-- ==========================================================================
-- Per-center program / track catalog (KET, PET, IELTS, Communication, …).
-- Replaces the hardcoded list in src/lib/programs.ts so each center can
-- rename / add / delete their own program names. Run after schema.sql.
--
-- classes.program continues to be a free-form text column. It stores the
-- *label* of the program. When the admin renames a program we cascade-update
-- every class that uses the old label inside the same UPDATE transaction
-- (handled in the server action). When a program is deleted, classes that
-- referenced it have their `program` cleared.

create table if not exists public.center_programs (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (center_id, label)
);

create index if not exists center_programs_center_id_idx
  on public.center_programs(center_id);

alter table public.center_programs enable row level security;

-- Admin can manage their center's program catalog.
drop policy if exists "center_programs_admin_all" on public.center_programs;
create policy "center_programs_admin_all"
  on public.center_programs for all
  using (
    public.current_user_role() = 'admin'
    and center_id = public.current_user_center_id()
  )
  with check (
    public.current_user_role() = 'admin'
    and center_id = public.current_user_center_id()
  );

-- Teachers can read programs in their own center (used to render dropdowns
-- if/when teachers ever edit class-program inline).
drop policy if exists "center_programs_teacher_read" on public.center_programs;
create policy "center_programs_teacher_read"
  on public.center_programs for select
  using (
    public.current_user_role() in ('teacher', 'admin')
    and center_id = public.current_user_center_id()
  );

-- ==========================================================================
-- attendance.sql
-- ==========================================================================
-- Per-student attendance per lesson (present / absent / late). Added to
-- student_lesson_updates so it lives alongside behavior + homework. Optional;
-- null = teacher didn't mark it (older lessons / forgot). Run after
-- schema.sql.

alter table public.student_lesson_updates
  add column if not exists attendance text;

do $$
begin
  alter table public.student_lesson_updates
    add constraint student_lesson_updates_attendance_check
    check (
      attendance in ('present', 'absent', 'late')
      or attendance is null
    );
exception when duplicate_object then null;
end $$;

-- ==========================================================================
-- feedback.sql
-- ==========================================================================
-- In-app feedback widget. Users (admin / teacher / parent) tap a
-- floating "Feedback" button, pick an emoji rating, optionally
-- type a comment. Submissions land in this table and feed the
-- /super-admin Feedback inbox.
--
-- Idempotent.

do $$ begin
  create type feedback_rating as enum ('sad', 'meh', 'happy');
exception when duplicate_object then null; end $$;

create table if not exists public.feedback (
  id uuid primary key default uuid_generate_v4(),
  -- center_id is nullable so demo users can submit too (they have
  -- a center_id but it's the shared demo center; we still want their
  -- feedback). SET NULL on center delete keeps the audit trail.
  center_id uuid references public.centers(id) on delete set null,
  -- user_id is nullable so anonymous/public-page feedback is possible
  -- later if we want to widen this widget's surface.
  user_id uuid references public.users(id) on delete set null,
  role text,
  rating feedback_rating not null,
  comment text,
  page text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists feedback_created_idx on public.feedback (created_at desc);
create index if not exists feedback_center_idx on public.feedback (center_id, created_at desc);

alter table public.feedback enable row level security;

-- Super-admin reads via service role only. No public-facing select
-- policy — we never want a teacher seeing other teachers' feedback.
-- Writes also go through the service role from a server action that
-- has already auth-gated the caller via requireRole.

-- ==========================================================================
-- founding-center.sql
-- ==========================================================================
-- Founding Center program: internal-only tier tracking for hand-picked
-- pilot customers (locked discounted rate, deeper feedback expected)
-- and the rare "Design Partner" relationship (free-forever in exchange
-- for ongoing product input).
--
-- The plan_tier column lives alongside subscription_status and
-- subscription_plan:
--   subscription_status  → 'trial' | 'active' | 'expired' | …
--   subscription_plan    → 'monthly' | 'six_months' | 'annual'  (paying tier)
--   plan_tier            → 'standard' | 'founding' | 'design_partner'  (this file)
--
-- The composite that the super-admin form actually picks decomposes
-- to (status, plan, plan_tier, trial_ends_at) — see createCenter for
-- the mapping.
--
-- Idempotent.

do $$ begin
  create type plan_tier as enum ('standard', 'founding', 'design_partner');
exception when duplicate_object then null; end $$;

alter table public.centers
  add column if not exists plan_tier plan_tier not null default 'standard';

-- Onboarding source — internal funnel attribution. Optional. Free
-- text rather than enum so a one-off ad campaign can be tracked
-- without a schema change.
alter table public.centers
  add column if not exists signup_source text;
alter table public.centers
  add column if not exists referral_note text;

create index if not exists centers_plan_tier_idx on public.centers (plan_tier)
  where plan_tier != 'standard';

-- Tiny key/value store for app-wide settings the super-admin needs
-- to tweak without a migration. First user: founding_center_cap
-- (the "5 of N spots filled" target on the overview widget).
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.app_settings enable row level security;
-- No public select / write policies — service role only. The super-
-- admin reads + writes through server actions in /super-admin.

insert into public.app_settings (key, value)
values ('founding_center_cap', to_jsonb(5))
on conflict (key) do nothing;

-- ==========================================================================
-- fix-rls-recursion.sql
-- ==========================================================================
-- Fix infinite-recursion in RLS for students / classes / lessons /
-- student_lesson_updates. Original policies cross-referenced each other
-- through `exists (select 1 from <other_table> ...)` which retriggered the
-- other table's RLS, causing recursion. Solution: wrap the cross-table
-- checks in SECURITY DEFINER helper functions that bypass RLS.

-- ==========================================================================
-- Helper functions
-- ==========================================================================

create or replace function public.is_teacher_of_class(p_class_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.classes
    where id = p_class_id and teacher_id = auth.uid()
  )
$$;

create or replace function public.is_parent_of_student_in_class(p_class_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.students
    where class_id = p_class_id and parent_user_id = auth.uid()
  )
$$;

create or replace function public.is_parent_of_student(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.students
    where id = p_student_id and parent_user_id = auth.uid()
  )
$$;

create or replace function public.lesson_class_id(p_lesson_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select class_id from public.lessons where id = p_lesson_id
$$;

-- ==========================================================================
-- Replace circular policies
-- ==========================================================================

drop policy if exists "classes_select" on public.classes;
create policy "classes_select"
  on public.classes for select
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (public.current_user_role() = 'teacher' and teacher_id = auth.uid())
      or (
        public.current_user_role() = 'parent'
        and public.is_parent_of_student_in_class(id)
      )
    )
  );

drop policy if exists "students_select" on public.students;
create policy "students_select"
  on public.students for select
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (
        public.current_user_role() = 'teacher'
        and public.is_teacher_of_class(class_id)
      )
      or (
        public.current_user_role() = 'parent'
        and parent_user_id = auth.uid()
      )
    )
  );

drop policy if exists "lessons_select" on public.lessons;
create policy "lessons_select"
  on public.lessons for select
  using (
    public.current_user_role() = 'admin'
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(class_id)
    )
    or (
      public.current_user_role() = 'parent'
      and public.is_parent_of_student_in_class(class_id)
    )
  );

drop policy if exists "lessons_teacher_write" on public.lessons;
create policy "lessons_teacher_write"
  on public.lessons for all
  using (
    public.current_user_role() = 'admin'
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(class_id)
    )
  )
  with check (
    teacher_id = auth.uid()
    or public.current_user_role() = 'admin'
  );

drop policy if exists "slu_select" on public.student_lesson_updates;
create policy "slu_select"
  on public.student_lesson_updates for select
  using (
    public.current_user_role() = 'admin'
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
    or (
      public.current_user_role() = 'parent'
      and public.is_parent_of_student(student_id)
    )
  );

drop policy if exists "slu_teacher_write" on public.student_lesson_updates;
create policy "slu_teacher_write"
  on public.student_lesson_updates for all
  using (
    public.current_user_role() = 'admin'
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
  )
  with check (
    public.current_user_role() = 'admin'
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
  );

-- ==========================================================================
-- 2026-07-02-audit-fixes.sql
-- ==========================================================================
-- ==========================================================================
-- 2026-07-02 security & correctness audit fixes
-- Apply in the Supabase SQL editor AFTER all prior migrations.
-- Idempotent: safe to run more than once.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- C1 (CRITICAL) — restore center scoping on lessons / student_lesson_updates.
--
-- fix-rls-recursion.sql reduced the ADMIN branch of these four policies to a
-- bare role check with no center scoping (and, unlike classes/students, there
-- is no outer center_id wrapper). Because the anon key + Supabase URL ship in
-- the client bundle, any authenticated admin could read/write EVERY center's
-- lessons and per-student notes via direct PostgREST calls; any teacher could
-- INSERT lessons into any center's class (WITH CHECK only verified teacher_id).
--
-- lessons / student_lesson_updates have no center_id column — they reach it
-- through class_id -> classes. We add a SECURITY DEFINER helper that resolves
-- a class's center_id (bypassing RLS, no recursion) and re-scope the admin
-- branch to it. The teacher branch uses is_teacher_of_class (already tied to
-- classes.teacher_id = auth.uid(), so implicitly single-center) and the parent
-- branch is unchanged.
-- --------------------------------------------------------------------------

create or replace function public.class_center_id(p_class_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select center_id from public.classes where id = p_class_id
$$;

drop policy if exists "lessons_select" on public.lessons;
create policy "lessons_select"
  on public.lessons for select
  using (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(class_id) = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(class_id)
    )
    or (
      public.current_user_role() = 'parent'
      and public.is_parent_of_student_in_class(class_id)
    )
  );

drop policy if exists "lessons_teacher_write" on public.lessons;
create policy "lessons_teacher_write"
  on public.lessons for all
  using (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(class_id) = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(class_id)
    )
  )
  with check (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(class_id) = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(class_id)
    )
  );

drop policy if exists "slu_select" on public.student_lesson_updates;
create policy "slu_select"
  on public.student_lesson_updates for select
  using (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(public.lesson_class_id(lesson_id))
            = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
    or (
      public.current_user_role() = 'parent'
      and public.is_parent_of_student(student_id)
    )
  );

drop policy if exists "slu_teacher_write" on public.student_lesson_updates;
create policy "slu_teacher_write"
  on public.student_lesson_updates for all
  using (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(public.lesson_class_id(lesson_id))
            = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
  )
  with check (
    (
      public.current_user_role() = 'admin'
      and public.class_center_id(public.lesson_class_id(lesson_id))
            = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.is_teacher_of_class(public.lesson_class_id(lesson_id))
    )
  );

-- --------------------------------------------------------------------------
-- H5 (HIGH) — parent/teacher could rewrite ANY message body via the broad
-- ptm_update_read UPDATE policy (no WITH CHECK, no column restriction).
--
-- Postgres RLS can't restrict which columns an UPDATE touches, so we drop the
-- broad policy and move "mark as read" to a SECURITY DEFINER function that
-- only ever writes read_at, and only for messages the caller may see and did
-- not send. The admin FOR ALL policy (ptm_admin_all, center-scoped) is kept —
-- center operators manage their own center's data.
-- --------------------------------------------------------------------------

drop policy if exists "ptm_update_read" on public.parent_teacher_messages;

create or replace function public.mark_messages_read(p_student_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.parent_teacher_messages m
  set read_at = now()
  where m.student_id = p_student_id
    and m.read_at is null
    and m.sender_user_id <> auth.uid()   -- only mark messages you RECEIVED
    and (
      (
        public.current_user_role() = 'parent'
        and exists (
          select 1 from public.students s
          where s.id = m.student_id and s.parent_user_id = auth.uid()
        )
      )
      or (
        public.current_user_role() = 'teacher'
        and exists (
          select 1 from public.students s
          join public.classes c on c.id = s.class_id
          where s.id = m.student_id and c.teacher_id = auth.uid()
        )
      )
      or (
        public.current_user_role() = 'admin'
        and m.center_id = public.current_user_center_id()
      )
    );
end;
$$;

revoke all on function public.mark_messages_read(uuid) from public;
grant execute on function public.mark_messages_read(uuid) to authenticated;

-- --------------------------------------------------------------------------
-- L3 (LOW) — worksheets_write was FOR ALL to any admin/teacher in the center,
-- so the app-layer "teachers can only delete their own uploads" check was
-- bypassable via direct PostgREST. Split into granular policies that enforce
-- upload-ownership for teachers at the RLS layer.
-- --------------------------------------------------------------------------

drop policy if exists "worksheets_write" on public.worksheets;

create policy "worksheets_insert"
  on public.worksheets for insert
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  );

create policy "worksheets_update"
  on public.worksheets for update
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (public.current_user_role() = 'teacher' and uploaded_by = auth.uid())
    )
  )
  with check (center_id = public.current_user_center_id());

create policy "worksheets_delete"
  on public.worksheets for delete
  using (
    center_id = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (public.current_user_role() = 'teacher' and uploaded_by = auth.uid())
    )
  );

-- --------------------------------------------------------------------------
-- M8 (MEDIUM) — no idempotency on lesson creation. A network retry / double
-- submit / two tabs creates duplicate lessons that double-count homework and
-- attendance on the parent report. Enforce one lesson per class per date.
--
-- If real historical data already violates this (two legit lessons same day),
-- this index creation will fail — in that case switch the model to an
-- app-generated idempotency key instead. Dedupe defensively first.
-- --------------------------------------------------------------------------

with ranked as (
  select id,
         row_number() over (
           partition by class_id, lesson_date
           order by created_at asc
         ) as rn
  from public.lessons
)
delete from public.student_lesson_updates
where lesson_id in (select id from ranked where rn > 1);

with ranked as (
  select id,
         row_number() over (
           partition by class_id, lesson_date
           order by created_at asc
         ) as rn
  from public.lessons
)
delete from public.lessons
where id in (select id from ranked where rn > 1);

create unique index if not exists lessons_class_date_uniq
  on public.lessons (class_id, lesson_date);

-- --------------------------------------------------------------------------
-- M2 (MEDIUM) — CSV-imported accounts get an auto-generated temp password
-- that was never force-rotated, leaving a permanent standing credential
-- (often relayed over Zalo/paper). Add a flag so the app can require a
-- password change on first login. Set true only for generated passwords;
-- cleared when the user sets their own password on /reset-password.
-- --------------------------------------------------------------------------

alter table public.users
  add column if not exists must_change_password boolean not null default false;

-- ==========================================================================
-- comment-suggestions.sql
-- ==========================================================================
-- Comment suggestions — a pre-written, human-authored comment bank for the
-- teacher lesson form. Nothing is generated at write-time; the app only
-- rotates which suggestions are SHOWN (5 per category per calendar day,
-- deterministic — see src/lib/comment-suggestions.ts). Tapping one drops
-- its text into the normal individual_note field, which saves through the
-- existing lesson path unchanged.
--
-- Each row carries a `lang` ('vi'/'en'); the form shows the bank matching
-- the teacher's UI locale (Vietnamese is the product default, so the pool
-- is seeded in both languages — the note text goes verbatim to parents).
--
-- Suggestions are GLOBAL across centers for now. To add per-center custom
-- suggestions later: add a nullable `center_id uuid references
-- public.centers(id) on delete cascade`, treat NULL as "global", and widen
-- the select policy to `center_id is null or center_id =
-- public.current_user_center_id()`. No UI for that yet by design.
--
-- Content is managed via migrations / service role only — there are no
-- insert/update/delete policies on purpose.

create table if not exists public.comment_suggestions (
  id uuid primary key default uuid_generate_v4(),
  category text not null check (
    category in ('positive', 'needs_improvement', 'participation', 'homework')
  ),
  lang text not null default 'en' check (lang in ('vi', 'en')),
  text text not null check (char_length(text) > 0 and char_length(text) <= 500),
  active boolean not null default true,
  sort_order int,
  created_at timestamptz not null default now(),
  -- Also what makes the seed below idempotent (on conflict do nothing).
  constraint comment_suggestions_category_text_uniq unique (category, text)
);

create index if not exists comment_suggestions_lang_category_idx
  on public.comment_suggestions (lang, category)
  where active;

alter table public.comment_suggestions enable row level security;

-- Teachers and admins read the active bank; parents have no reason to see
-- it (they only ever see the final saved note text). Global by design —
-- the one deliberate exception to per-center query scoping (see header).
drop policy if exists "comment_suggestions_select" on public.comment_suggestions;
create policy "comment_suggestions_select"
  on public.comment_suggestions for select
  using (
    active
    and public.current_user_role() in ('teacher', 'admin')
  );

-- ==========================================================================
-- Seed — starter pool, English + Vietnamese. Idempotent via the
-- (category, text) unique key.
-- ==========================================================================

insert into public.comment_suggestions (category, lang, text, sort_order) values
  ('positive', 'en', 'Had a great attitude in class today.', 1),
  ('positive', 'en', 'Really engaged with today''s activities.', 2),
  ('positive', 'en', 'Showed good improvement with today''s vocabulary.', 3),
  ('positive', 'en', 'Helped classmates during group work.', 4),
  ('positive', 'en', 'Answered confidently during today''s lesson.', 5),
  ('positive', 'en', 'Stayed focused throughout the whole class.', 6),
  ('positive', 'en', 'Did a great job with today''s speaking activity.', 7),
  ('positive', 'en', 'Picked up today''s new words quickly.', 8),
  ('positive', 'en', 'Was very participative during games today.', 9),
  ('positive', 'en', 'Showed nice progress with pronunciation today.', 10),
  ('positive', 'en', 'Worked well with a partner today.', 11),
  ('positive', 'en', 'Completed all tasks with a positive attitude.', 12),
  ('positive', 'en', 'Asked great questions during the lesson.', 13),
  ('positive', 'en', 'Was a good listener today.', 14),
  ('positive', 'en', 'Showed confidence presenting to the class.', 15),
  ('needs_improvement', 'en', 'Had some trouble focusing today — worth keeping an eye on at home.', 1),
  ('needs_improvement', 'en', 'Struggled a bit with today''s vocabulary; some review at home would help.', 2),
  ('needs_improvement', 'en', 'Seemed a little tired today, participation was lower than usual.', 3),
  ('needs_improvement', 'en', 'Could use some extra practice with today''s grammar point.', 4),
  ('needs_improvement', 'en', 'Had some difficulty following instructions today.', 5),
  ('needs_improvement', 'en', 'Needs a bit more encouragement to speak up in class.', 6),
  ('needs_improvement', 'en', 'Found today''s listening activity challenging.', 7),
  ('needs_improvement', 'en', 'Was a little distracted during group work today.', 8),
  ('needs_improvement', 'en', 'Could benefit from reviewing today''s lesson at home.', 9),
  ('needs_improvement', 'en', 'Had some trouble staying on task today.', 10),
  ('participation', 'en', 'Volunteered to answer several times today.', 1),
  ('participation', 'en', 'Was a bit quieter than usual today.', 2),
  ('participation', 'en', 'Took a little time to warm up but joined in well.', 3),
  ('participation', 'en', 'Worked actively in today''s pair/group activities.', 4),
  ('participation', 'en', 'Needed some encouragement to join in today.', 5),
  ('participation', 'en', 'Was one of the first to raise a hand today.', 6),
  ('participation', 'en', 'Preferred listening over speaking today, which is okay.', 7),
  ('participation', 'en', 'Got more involved as the class went on.', 8),
  ('homework', 'en', 'Completed homework fully and correctly.', 1),
  ('homework', 'en', 'Homework was mostly done, a few items missed.', 2),
  ('homework', 'en', 'Homework wasn''t completed today.', 3),
  ('homework', 'en', 'Homework showed good effort.', 4),
  ('homework', 'en', 'A reminder about today''s homework was given.', 5),
  ('homework', 'en', 'Homework had some errors — happy to review together next class.', 6),
  ('positive', 'vi', 'Hôm nay con có thái độ học tập rất tốt.', 1),
  ('positive', 'vi', 'Con tham gia rất tích cực các hoạt động hôm nay.', 2),
  ('positive', 'vi', 'Con tiến bộ rõ với phần từ vựng hôm nay.', 3),
  ('positive', 'vi', 'Con biết giúp đỡ các bạn khi làm việc nhóm.', 4),
  ('positive', 'vi', 'Con trả lời rất tự tin trong buổi học hôm nay.', 5),
  ('positive', 'vi', 'Con tập trung tốt suốt cả buổi học.', 6),
  ('positive', 'vi', 'Con làm rất tốt hoạt động luyện nói hôm nay.', 7),
  ('positive', 'vi', 'Con tiếp thu từ mới hôm nay rất nhanh.', 8),
  ('positive', 'vi', 'Con tham gia trò chơi hôm nay rất sôi nổi.', 9),
  ('positive', 'vi', 'Phát âm của con hôm nay tiến bộ rõ rệt.', 10),
  ('positive', 'vi', 'Con phối hợp với bạn rất tốt trong giờ học hôm nay.', 11),
  ('positive', 'vi', 'Con hoàn thành mọi nhiệm vụ với thái độ tích cực.', 12),
  ('positive', 'vi', 'Con đặt những câu hỏi rất hay trong giờ học.', 13),
  ('positive', 'vi', 'Hôm nay con lắng nghe rất tốt.', 14),
  ('positive', 'vi', 'Con tự tin khi trình bày trước lớp.', 15),
  ('needs_improvement', 'vi', 'Hôm nay con hơi khó tập trung — gia đình lưu ý thêm ở nhà giúp con nhé.', 1),
  ('needs_improvement', 'vi', 'Con còn gặp khó với từ vựng hôm nay; ôn lại ở nhà sẽ giúp con nhiều.', 2),
  ('needs_improvement', 'vi', 'Hôm nay con có vẻ hơi mệt, tham gia ít hơn mọi khi.', 3),
  ('needs_improvement', 'vi', 'Con cần luyện thêm phần ngữ pháp của buổi học hôm nay.', 4),
  ('needs_improvement', 'vi', 'Hôm nay con còn gặp khó khi làm theo hướng dẫn.', 5),
  ('needs_improvement', 'vi', 'Con cần được động viên thêm để mạnh dạn phát biểu trong lớp.', 6),
  ('needs_improvement', 'vi', 'Bài nghe hôm nay còn hơi khó với con.', 7),
  ('needs_improvement', 'vi', 'Con hơi mất tập trung khi làm việc nhóm hôm nay.', 8),
  ('needs_improvement', 'vi', 'Con nên ôn lại bài học hôm nay ở nhà.', 9),
  ('needs_improvement', 'vi', 'Hôm nay con còn khó duy trì sự tập trung vào nhiệm vụ.', 10),
  ('participation', 'vi', 'Hôm nay con xung phong trả lời nhiều lần.', 1),
  ('participation', 'vi', 'Hôm nay con trầm hơn mọi khi một chút.', 2),
  ('participation', 'vi', 'Con cần chút thời gian làm quen nhưng sau đó tham gia rất tốt.', 3),
  ('participation', 'vi', 'Con hoạt động tích cực trong các hoạt động cặp/nhóm hôm nay.', 4),
  ('participation', 'vi', 'Hôm nay con cần được khích lệ mới tham gia hoạt động.', 5),
  ('participation', 'vi', 'Con là một trong những bạn giơ tay phát biểu đầu tiên hôm nay.', 6),
  ('participation', 'vi', 'Hôm nay con thích lắng nghe hơn là nói — điều này hoàn toàn bình thường.', 7),
  ('participation', 'vi', 'Càng về cuối buổi con càng tham gia tích cực hơn.', 8),
  ('homework', 'vi', 'Con hoàn thành đầy đủ và chính xác bài tập về nhà.', 1),
  ('homework', 'vi', 'Bài tập về nhà làm gần đủ, còn sót một vài phần.', 2),
  ('homework', 'vi', 'Hôm nay con chưa hoàn thành bài tập về nhà.', 3),
  ('homework', 'vi', 'Bài tập về nhà cho thấy con đã rất cố gắng.', 4),
  ('homework', 'vi', 'Con đã được nhắc về bài tập về nhà hôm nay.', 5),
  ('homework', 'vi', 'Bài tập còn một số lỗi — buổi sau lớp sẽ cùng xem lại.', 6)
on conflict (category, text) do nothing;

-- ==========================================================================
-- worksheet-categories.sql
-- ==========================================================================
-- Worksheet categories — lightweight labels so the library and the lesson
-- form's picker can be browsed by kind instead of one long list. Nullable
-- text + CHECK (the convention for incrementally-added values, like
-- student_lesson_updates.attendance): existing rows stay NULL and the UI
-- shows them under "Other". Labels are i18n'd in the app
-- (src/messages/*.json → worksheets.categories.*); the DB stores the key.

alter table public.worksheets
  add column if not exists category text
  check (
    category is null
    or category in (
      'grammar', 'vocabulary', 'reading', 'writing', 'listening',
      'speaking', 'games', 'homework', 'exam', 'other'
    )
  );

-- ==========================================================================
-- student-photos.sql
-- ==========================================================================
-- Student photos — teachers photograph class moments and tag the students
-- in the shot; parents see (only) their own child's photos in the child's
-- timeline. One photo can be tagged to multiple students.
--
-- STORAGE STANCE (mirrors db/2026-07-02-worksheets-private.sql): the
-- `student-photos` bucket is born PRIVATE and gets NO storage.objects
-- policies at all — clients never talk to Storage directly. Uploads go
-- through the server action (service role, after requireRole + roster
-- validation) and reads happen via short-lived signed URLs minted by the
-- server ONLY for rows the caller could already read through table RLS
-- (src/lib/photo-url.ts). Guessing a storage path yields nothing without
-- a valid signature. Bucket-level file_size_limit / allowed_mime_types are
-- a hard backstop enforced by Supabase Storage itself, independent of app
-- code.

-- ==========================================================================
-- Bucket (private; 5MB cap; images only)
-- ==========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'student-photos',
  'student-photos',
  false,
  5242880, -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

-- ==========================================================================
-- Tables
-- ==========================================================================

create table if not exists public.student_photos (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  -- SET NULL like worksheets.uploaded_by: removing a teacher keeps the
  -- photos (parents keep the record); admins still manage them.
  uploaded_by uuid references public.users(id) on delete set null,
  -- Path convention: {center_id}/{photo_id}.{ext}. The CHECK pins every
  -- row's object path inside its own center's storage prefix — without it,
  -- a teacher hitting PostgREST directly could insert/update a row whose
  -- storage_path points into ANOTHER center's prefix and have the server
  -- sign it for them. A table constraint (not just a policy) so it also
  -- binds service-role writes.
  storage_path text not null
    check (storage_path like center_id::text || '/%'),
  caption text check (caption is null or char_length(caption) <= 200),
  -- Date the photo belongs to in the timeline (VN-local; set by the app).
  taken_at date not null default current_date,
  created_at timestamptz not null default now()
);
create index if not exists student_photos_center_idx
  on public.student_photos (center_id);
create index if not exists student_photos_uploaded_by_idx
  on public.student_photos (uploaded_by);

-- One photo ↔ many students (group shots). Deleting a photo cascades its
-- tags; the storage object is removed by the delete server action.
create table if not exists public.student_photo_tags (
  photo_id uuid not null references public.student_photos(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (photo_id, student_id)
);
create index if not exists student_photo_tags_student_idx
  on public.student_photo_tags (student_id);

-- ==========================================================================
-- RLS helper functions (SECURITY DEFINER to break policy recursion, same
-- rationale as db/fix-rls-recursion.sql)
-- ==========================================================================

create or replace function public.photo_center_id(p_photo_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select center_id from public.student_photos where id = p_photo_id
$$;

create or replace function public.photo_uploaded_by(p_photo_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select uploaded_by from public.student_photos where id = p_photo_id
$$;

-- Is the current user the parent of at least one student tagged on this
-- photo? THE rule that scopes parents to their own child's photos.
create or replace function public.is_parent_of_tagged_student(p_photo_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.student_photo_tags t
    join public.students s on s.id = t.student_id
    where t.photo_id = p_photo_id
      and s.parent_user_id = auth.uid()
  )
$$;

-- Does the current user teach the class this student is in? (Same
-- teacher→class→student chain as students_select.)
create or replace function public.is_teacher_of_student(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.students s
    join public.classes c on c.id = s.class_id
    where s.id = p_student_id
      and c.teacher_id = auth.uid()
  )
$$;

create or replace function public.student_center_id(p_student_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select center_id from public.students where id = p_student_id
$$;

-- ==========================================================================
-- RLS: student_photos
--   admin   → all photos in their center
--   teacher → photos they uploaded, in their center
--   parent  → READ ONLY, and only photos tagged to their own child(ren)
-- (super-admin/platform ops use the service role, which bypasses RLS.)
-- ==========================================================================

alter table public.student_photos enable row level security;

drop policy if exists "student_photos_select" on public.student_photos;
create policy "student_photos_select"
  on public.student_photos for select
  using (
    (
      public.current_user_role() = 'admin'
      and center_id = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and uploaded_by = auth.uid()
      and center_id = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'parent'
      and center_id = public.current_user_center_id()
      and public.is_parent_of_tagged_student(id)
    )
  );

drop policy if exists "student_photos_insert" on public.student_photos;
create policy "student_photos_insert"
  on public.student_photos for insert
  with check (
    center_id = public.current_user_center_id()
    and uploaded_by = auth.uid()
    and public.current_user_role() in ('teacher', 'admin')
  );

drop policy if exists "student_photos_update" on public.student_photos;
create policy "student_photos_update"
  on public.student_photos for update
  using (
    (
      public.current_user_role() = 'admin'
      and center_id = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and uploaded_by = auth.uid()
      and center_id = public.current_user_center_id()
    )
  )
  -- WITH CHECK mirrors USING so the NEW row must still satisfy the same
  -- ownership rule — otherwise a teacher could reassign uploaded_by (handing
  -- delete rights to someone else / orphaning the photo to admin-only).
  with check (
    (
      public.current_user_role() = 'admin'
      and center_id = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and uploaded_by = auth.uid()
      and center_id = public.current_user_center_id()
    )
  );

drop policy if exists "student_photos_delete" on public.student_photos;
create policy "student_photos_delete"
  on public.student_photos for delete
  using (
    (
      public.current_user_role() = 'admin'
      and center_id = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and uploaded_by = auth.uid()
      and center_id = public.current_user_center_id()
    )
  );

-- No parent write policies exist → parents cannot insert/update/delete.

-- ==========================================================================
-- RLS: student_photo_tags
--   admin   → tags on photos in their center
--   teacher → tags on their own photos; may only tag students of classes
--             they teach (existing teacher→class→student scoping)
--   parent  → READ ONLY, only tag rows pointing at their own child
-- ==========================================================================

alter table public.student_photo_tags enable row level security;

drop policy if exists "student_photo_tags_select" on public.student_photo_tags;
create policy "student_photo_tags_select"
  on public.student_photo_tags for select
  using (
    (
      public.current_user_role() = 'admin'
      and public.photo_center_id(photo_id) = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'teacher'
      and public.photo_uploaded_by(photo_id) = auth.uid()
      -- Center check too: a teacher moved to another center must not keep
      -- reading tag rows from photos they uploaded at the old center.
      and public.photo_center_id(photo_id) = public.current_user_center_id()
    )
    or (
      public.current_user_role() = 'parent'
      and public.is_parent_of_student(student_id)
    )
  );

drop policy if exists "student_photo_tags_insert" on public.student_photo_tags;
create policy "student_photo_tags_insert"
  on public.student_photo_tags for insert
  with check (
    -- The tagged student must live in the same center as the photo, and
    -- that center must be the caller's own.
    public.photo_center_id(photo_id) = public.current_user_center_id()
    and public.student_center_id(student_id) = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (
        public.current_user_role() = 'teacher'
        and public.photo_uploaded_by(photo_id) = auth.uid()
        and public.is_teacher_of_student(student_id)
      )
    )
  );

drop policy if exists "student_photo_tags_delete" on public.student_photo_tags;
create policy "student_photo_tags_delete"
  on public.student_photo_tags for delete
  using (
    public.photo_center_id(photo_id) = public.current_user_center_id()
    and (
      public.current_user_role() = 'admin'
      or (
        public.current_user_role() = 'teacher'
        and public.photo_uploaded_by(photo_id) = auth.uid()
      )
    )
  );
