-- Worksheet library: PDFs / images uploaded by a center, attachable to lessons.
-- Run after schema.sql. Re-running this file is safe and will also migrate an
-- existing deployment from the old world-readable bucket to the private one.

-- Storage bucket is PRIVATE. Worksheets are lesson materials scoped to a single
-- center, so they must never be reachable by a guessed or leaked public URL —
-- otherwise one center could open another center's files. Files are served via
-- short-lived signed URLs minted server-side (see src/lib/worksheets.ts), only
-- after the caller has been authorized and center-scoped by RLS.
--
-- `on conflict do update` flips an already-public bucket (from an earlier
-- version of this app) back to private.
insert into storage.buckets (id, name, public)
values ('worksheets', 'worksheets', false)
on conflict (id) do update set public = false;

-- Drop the old world-readable policy. Signed URLs are generated by the
-- service-role client, which bypasses storage RLS, so no select policy on
-- storage.objects is needed for this bucket.
drop policy if exists "Public can read worksheets" on storage.objects;

-- Library table.
create table if not exists public.worksheets (
  id uuid primary key default uuid_generate_v4(),
  center_id uuid not null references public.centers(id) on delete cascade,
  uploaded_by uuid references public.users(id) on delete set null,
  name text not null,
  storage_path text not null,
  -- Legacy column from when the bucket was public. No longer used for access
  -- (files are served via signed URLs derived from storage_path); kept nullable
  -- for backward compatibility with existing rows.
  public_url text,
  file_type text not null,
  size_bytes int not null,
  created_at timestamptz not null default now()
);

create index if not exists worksheets_center_idx on public.worksheets(center_id);

-- Existing deployments: relax the old NOT NULL on public_url (see note above).
alter table public.worksheets alter column public_url drop not null;

alter table public.worksheets enable row level security;

drop policy if exists "worksheets_select" on public.worksheets;
create policy "worksheets_select"
  on public.worksheets for select
  using (center_id = public.current_user_center_id());

drop policy if exists "worksheets_write" on public.worksheets;
create policy "worksheets_write"
  on public.worksheets for all
  using (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  )
  with check (
    center_id = public.current_user_center_id()
    and public.current_user_role() in ('admin', 'teacher')
  );

-- Attach a worksheet to a lesson (single worksheet per lesson for now).
alter table public.lessons
  add column if not exists worksheet_id uuid
    references public.worksheets(id) on delete set null;
